### PR TITLE
Escape windows path during metro transform

### LINKED ISSUE #610: Build Hangs in V4
**Describe the bug**
I followed the expo-router instructions for v4.
When including the css file in _layout.css the build hangs

**To Reproduce**
1. Clone this repo https://github.com/revolution42/nativewind-demo
2. Run yarn start
3. Open in web mode (W)

**Screenshots**
image
Build will stay like this

### PR DESCRIPTION
**Pull request by sxxov**
Fixes #610

### CODE REVIEW

**Comment by marklawlor** [comment]
This seems somewhat wrong to me. NodeJS on windows accepts UNIX style file-paths for `require()` statements, so this shouldn't even be a windows path. I believe we should be converting the windows absolute path to a UNIX path here https://github.com/marklawlor/nativewind/blob/3610853e81ee2f379d81b8958dc128b4343764dd/packages/nativewind/src/metro/index.ts#L91-L94

**Comment by sxxov** [comment]
@marklawlor `require` does support windows paths, it’s just the path written into script:

```diff
- require(‘C:\folder\global.css’)
+ require(‘C:\\folder\\global.css’)
```

Changing it to unix paths up there is a good idea as well, but might be a bit more work, since we now have to work with relative paths on windows.

**Comment by neverson-silva** [comment]
I'm having this issue either on windows

**Comment by neverson-silva** [comment]
@marklawlor is there any estimate for when this fix will be approved? I made the same adjustment locally (in the node_modules folder itself) and it worked on Windows?

**Comment by JorrinKievit** [comment]
Can also confirm that this fix worked on my Windows machine

**Comment by HGCollier** [comment]
Any reason this isn't merged yet?

**Pull request merged**
