### PR TITLE
v3

### LINKED ISSUE #233: `group` not working
**Describe the bug**
Below is a snippet of the code, where I have a parent `Pressable` with the `group` class and then the children (in here just one for demo purposes) use `group-active-*`. However, when I tap the button on a native device, I don't see anything change, even though I get the `"pressed"` message.

```tsx
      <Pressable
        className='p-2 select-none items-center flex-row group'
        onPress={() => {
          console.log('pressed');
        }}>
        <Text className='text-[#21232F] group-active:text-[#FF3367] font-[Lato-Medium] ml-[10px]'>
          Primary to All
        </Text>
    </Pressable>
```

**To Reproduce**
1. Create basic project with NativeWind support
2. Create a page with the snippet above embedded in it
3. Tap button on native devices

**Expected behavior**
I'd expect the text to turn pink when I tap the button (which is what happens on Web).

### LINKED ISSUE #234: `web:` and `native:` not working
**Describe the bug**
I was trying to apply a margin to only web, but when I used `web:ml-5` it didn't work.
I've also noticed if I tried `ml-0 native:ml-5` I couldn't get it to work.

My workaround to get it to work was to use: `ml-5 ios:ml-0 android:ml-0`.

**To Reproduce**
1. Create React Native app with NativeWind enabled
2. Try to apply a margin to only native or web using the platform prefixes

**Expected behavior**
Would expect `web:` to apply the style to web and not other platforms. Same for `native:`.

**Additional context**
My Expo project is configured to use NativeWind for web without the native translations, if that helps.

### LINKED ISSUE #235: Babel caching issues
It appears some users are being forced to reset their Babel caches often, especially while testing `tailwind.config.js` changes.

I'm aware of this and working on a solution.

### LINKED ISSUE #246: Slow app startup after bundle has been created
**Describe the bug**
Very slow startup performance after implementing this library. After metro has finished building the bundle it will take like 10 seconds to launch the app.

**Expected behavior**
Fast startup performance after bundle has been created.

### LINKED ISSUE #254: Alternative way to use className in typescript
Hi, with your typescript solution, in my custom components i should always extend my props interface with one of "base" interfaces like ViewProps, TextProps... But im not aways passing all props to my custom component, so it can lead to wrong intellisense suggestions.

You can use className in all components just by adding to app.d.ts:

```
declare namespace JSX {
    interface IntrinsicAttributes {
        className?: string
    }
}
```

Great project! I will use it in our production app.

### LINKED ISSUE #261: Error on toggeling dark theme on expo
When i try to toggle dark mode i get this error

Also  I followed all steps on installation.

### PR DESCRIPTION
**Pull request by marklawlor**
See #308 for more information

Fixes #233, 
Fixes #234 
Fixes #235 
Fixes #246 
Fixes #254 
Fixes #261

### CODE REVIEW

**Comment by nandorojo** [comment]
I'd like to advocate for documenting the usage of `.dark` and `:root` via tailwind plugin, rather than using `.css` files. If possible, I also think it would be good to have a `nativewind/web` plugin that injects the `@tailwind base...` styles. React Native Web should discourage using `.css` files.

**Comment by marklawlor** [comment]
Thanks for the feedback - testing a different approach

**Comment by jgornick** [comment]
@marklawlor Today we actually reverted our JS only approach in favor of the CSS approach. We went with a CSS approach for our consumers who want to create their own custom styles that are composed of utility classes provided by tailwind:

```css
.my-custom-class {
  @apply p-0 m-0
}
```

This allows our consumers of our utility style library to continue to use the design system set values without having to write the declarations manually.

**Comment by marklawlor** [comment]
The `.css` import is now optional in NativeWind 3

**Comment by marklawlor** [comment]
@koka0012 Aiming for ~1month, with a Release Candidate sometime before then

Things still left to do
- [ ] Finish rewriting theme functions to work with variables
- [ ] Write more units tests
- [ ] Update withExpo to use new format
- [ ] Update withExpo to work with CSS on web
- [ ] Update documentation of existing classes
- [ ] Update documentation for project setup
- [ ] Create documentation for variables
- [ ] Update documentation for Dark mode
- [ ] Update documentation for web projects

**Comment by jgornick** [comment]
Amazing work @marklawlor! Thank you for your efforts!

**Comment by marklawlor** [comment]
New breaking feature:

`group-isolate`/`parent` are being completely removed. NativeWind will support Tailwind's 3.2 named groups feature instead

**Comment by jgornick** [comment]
Hey @marklawlor! Can you provide an example how one might provide variables for the style sheet to reference?

If I'm understanding the implementation correctly, the values defined in the style sheet are references to variables. So when a style sheet is compiled (might be wrong word), it is following the references to set the value. This would be similar to how tailwind CSS works where you can set values in your theme configuration to `var(--color-blue-50)`, which allows you to dynamically swap out variables without updating any references.

Maybe what I'm looking for is for the ability to do something like:

```typescript
NativeWindStyleSheet.setVariables({
  root: { ... },
  dark: { ... },
})
```

Again, thank you for all the awesome work you've been doing here!

**Comment by marklawlor** [comment]
@jgornick I'm going to initially keep the API simple, so setVariables can only set variables

```tsx
NativeWindStyleSheet.setVariables({
  --color-blue-50: ... 
})
```

Afterwards I'll consider `setLightVariables` and `setDarkVariables`

**Comment by koka0012** [comment]
When you install it on a existent aplication you get the following error:

```
TypeError: Cannot read properties of undefined (reading 'caller')
```

Here is the repo to reproduce the erro:
https://github.com/koka0012/learn

**Comment by marklawlor** [comment]
I don't expect any of the prerelease versions to be working in a typical manner. I'll update this issue when more information when I'm ready to provide it

**Comment by koka0012** [comment]
Thanks, I'll wait them. I'm really happy with this new version. I was able to make it work btw.

**Comment by marklawlor** [comment]
Added a section for `Variant support`. Please let me know if you have any feedback

**Comment by timedtext** [comment]
I happen to be refactoring components with “className variants”.
One of the problems is that tailwind won't automatically merge duplicate classNames.
For example:
``` ts
const button = cva(["text-base"], {
  variants: {
    size: {
      small: ["text-sm"],
    },
  },
});
 
button({ size: "small" }); //  'text-base text-sm'
```

I solved this problem with [this library](https://github.com/dcastil/tailwind-merge)

**Comment by marklawlor** [comment]
@timedtext I considered `tailwind-merge` but I think a better method is simply providing education, for example people can write their components like this.

```
const button = cva([], {
  variants: {
    size: {
      base: ["text-base"],
      small: ["text-sm"],
    },
  },
  defaultVariants: {
    size: "base"
  }
});
```

I know this is a simple example, but I think it works fine for most cases.The best thing about NativeWind is that it can re-use all the tooling for web. So if someone does have a complicated variant stack and would benefit from deduplicated classNames, then there's nothing stopping them using `cva` inside their component.

**Comment by timedtext** [comment]
Yes, it solves the problem, just a little verbose.

``` ts
clsv({
  base: tw`text-base font-medium web:select-none`,
  variants: {
    variant: {
      default: tw`text-${palette}-600`, 
      solid: tw`text-white`,
      text: tw`text-${palette}-600`, // verbose
      link: tw`text-${palette}-600 hover:underline active:opacity-70`,
    },
    loading: {
      true: 'opacity-0',
    },
  },
  defaultVariants: {
    variant: 'default',
  },
})
```

**Comment by timedtext** [comment]
On web, there is another situation that can also lead to conflicts.

``` ts
const StyledView = styled(View);

const Card = styled(() => {
  return <StyledView className="p-4" />;
});

<Card className="p-6" />; // duplicates "p-4 p-6"
```
This is how I solve it now, not exported as Styled Component.
``` ts
const Card = ({ containerClassName }) => {
  return <StyledView className={twMerge('p-4', containerClassName)} />;
};
```

**Comment by marklawlor** [comment]
Browsers are highly optimised and written in faster languages that Javascript. If NativeWind deduplicated `p-4 p-6` its slowing down the React render cycle and causing a blocking effect with no actual gain

**Comment by timedtext** [comment]
The browser doesn't seem to have solved [this problem](https://github.com/tailwindlabs/tailwindcss/issues/1010).
I couldn't figure out any other good way to solve this problem.

**Comment by marklawlor** [comment]
Ah so that's slightly different to your example. The issue is that `p-4 p-0` will have `p-4` applies has it has higher specificity (its ordered after `p-0` in the generated styles). I think I'm going to hold off on this for the moment, its not a use-case I've personally encountered very often, and when I do I simply use the [important modifier](https://tailwindcss.com/docs/configuration#important-modifier) to force my override.

**Comment by marklawlor** [comment]
Actually let me think about this some more. For Native there is no rule specificity - it always uses the last value. This generally isn't an issue as most people use prettier to organise their styles and/or just never run into this.

But adding variants does make it harder to manage. I should either add specificity to native styles or better manage the web ones.

**Comment by timedtext** [comment]
Do you think it's a good idea to do so?
``` ts
const Card = ({ containerClassName }) => {
  const baseClassName = "p-4";
  const userClassName = containerClassName .split(' ') .filter(Boolean) .map((x) => `!${x}`) .join(' '); // May need to be optimized
  return <StyledView className={`${baseClassName} ${userClassName}`} />;
};
```

**Comment by marklawlor** [comment]
Tailwind doesn't support dynamic class strings. https://tailwindcss.com/docs/content-configuration

**Comment by marklawlor** [comment]
Please refer to #308 for more information. This is now available via `nativewind@next`

**Comment by emmanuelchucks** [comment]
Great work. What's the plan for native flex-gap in React Native 0.71.0?

**Comment by pvinis** [comment]
👀

**Pull request closed without merging**
